export const ASSET_CATEGORIES = [
  {
    key: "stocks",
    name: "Stocks",
    description: "Company shares listed on stock exchanges.",
    status: "available",
    dataRoute: "/api/stocks",
    searchParam: "query",
    examples: ["HDFC Bank", "Reliance", "Apple"],
  },
  {
    key: "mutual_funds",
    name: "Mutual Funds",
    description: "Mutual fund schemes with NAV data.",
    status: "available",
    dataRoute: "/api/mutual-funds",
    searchParam: "query",
    examples: ["Parag Parikh", "HDFC", "Axis"],
  },
  {
    key: "etf",
    name: "ETF",
    description: "Exchange-traded funds.",
    status: "coming_soon",
    dataRoute: null,
    searchParam: null,
    examples: ["NIFTYBEES", "BANKBEES", "SPY"],
  },
  {
    key: "fixed_deposit",
    name: "Fixed Deposit",
    description: "Bank and NBFC fixed deposit products.",
    status: "coming_soon",
    dataRoute: null,
    searchParam: null,
    examples: ["SBI FD", "HDFC FD", "ICICI FD"],
  },
  {
    key: "metals",
    name: "Metals",
    description: "Precious metals like gold and silver.",
    status: "coming_soon",
    dataRoute: null,
    searchParam: null,
    examples: ["Gold", "Silver", "Platinum"],
  },
  {
    key: "ulip",
    name: "ULIP",
    description: "Unit linked insurance plans.",
    status: "coming_soon",
    dataRoute: null,
    searchParam: null,
    examples: ["ULIP growth plan", "ULIP balanced plan"],
  },
  {
    key: "cash",
    name: "Cash",
    description: "Cash balance or liquid holdings.",
    status: "coming_soon",
    dataRoute: null,
    searchParam: null,
    examples: ["Wallet cash", "Bank balance"],
  },
  {
    key: "others",
    name: "Others",
    description: "Other assets not covered by the listed categories.",
    status: "coming_soon",
    dataRoute: null,
    searchParam: null,
    examples: ["Real estate", "Crypto", "Bonds"],
  },
];
