export const MARKET_SYMBOLS = {
  nifty: {
    key: "nifty",
    symbol: "^NSEI",
    displayName: "NIFTY 50",
    type: "INDEX",
    exchange: "NSE",
    country: "India",
  },
  sensex: {
    key: "sensex",
    symbol: "^BSESN",
    displayName: "SENSEX",
    type: "INDEX",
    exchange: "BSE",
    country: "India",
  },
  banknifty: {
    key: "banknifty",
    symbol: "^NSEBANK",
    displayName: "BANK NIFTY",
    type: "INDEX",
    exchange: "NSE",
    country: "India",
  },
  nasdaq: {
    key: "nasdaq",
    symbol: "^IXIC",
    displayName: "NASDAQ Composite",
    type: "INDEX",
    exchange: "NASDAQ",
    country: "United States",
  },
  hdfcbank: {
    key: "hdfcbank",
    symbol: "HDFCBANK.NS",
    displayName: "HDFC Bank",
    type: "EQUITY",
    exchange: "NSE",
    country: "India",
  },
};

export const DEFAULT_MARKET_KEYS = Object.keys(MARKET_SYMBOLS);

export const TOP_SHARE_MARKET_SYMBOLS = [
  "RELIANCE.NS",
  "TCS.NS",
  "HDFCBANK.NS",
  "BHARTIARTL.NS",
  "ICICIBANK.NS",
  "SBIN.NS",
  "INFY.NS",
  "LICI.NS",
  "ITC.NS",
  "HINDUNILVR.NS",
  "LT.NS",
  "AXISBANK.NS",
  "KOTAKBANK.NS",
  "BAJFINANCE.NS",
  "MARUTI.NS",
  "ASIANPAINT.NS",
  "SUNPHARMA.NS",
  "NTPC.NS",
  "TITAN.NS",
  "ULTRACEMCO.NS",
  "ONGC.NS",
  "NESTLEIND.NS",
  "HCLTECH.NS",
  "WIPRO.NS",
  "TATAMOTORS.NS",
  "POWERGRID.NS",
  "ADANIENT.NS",
  "BAJAJFINSV.NS",
  "ADANIPORTS.NS",
  "JSWSTEEL.NS",
  "COALINDIA.NS",
  "TATASTEEL.NS",
  "TECHM.NS",
  "INDUSINDBK.NS",
  "GRASIM.NS",
  "HINDALCO.NS",
  "DRREDDY.NS",
  "EICHERMOT.NS",
  "CIPLA.NS",
  "BAJAJ-AUTO.NS",
  "DIVISLAB.NS",
  "HEROMOTOCO.NS",
  "BPCL.NS",
  "BRITANNIA.NS",
  "APOLLOHOSP.NS",
  "SHRIRAMFIN.NS",
  "SBILIFE.NS",
  "TRENT.NS",
  "ADANIGREEN.NS",
  "ADANIPOWER.NS",
  "PIDILITIND.NS",
  "DLF.NS",
  "GODREJCP.NS",
  "SIEMENS.NS",
  "INDIGO.NS",
  "DMART.NS",
  "HAL.NS",
  "BEL.NS",
  "LODHA.NS",
  "IRCTC.NS",
  "TVSMOTOR.NS",
  "ABB.NS",
  "PFC.NS",
  "RECLTD.NS",
  "BANKBARODA.NS",
  "CANBK.NS",
  "PNB.NS",
  "GAIL.NS",
  "NMDC.NS",
  "SAIL.NS",
  "INDUSTOWER.NS",
  "MOTHERSON.NS",
  "COLPAL.NS",
  "AMBUJACEM.NS",
  "ACC.NS",
  "AUROPHARMA.NS",
  "LUPIN.NS",
  "ZYDUSLIFE.NS",
  "TORNTPHARM.NS",
  "ABBOTINDIA.NS",
  "BIOCON.NS",
  "PAGEIND.NS",
  "BOSCHLTD.NS",
  "CUMMINSIND.NS",
  "MRF.NS",
  "POLYCAB.NS",
  "HAVELLS.NS",
  "DABUR.NS",
  "MARICO.NS",
  "TATACONSUM.NS",
  "ICICIPRULI.NS",
  "HDFCLIFE.NS",
  "MCDOWELL-N.NS",
  "VEDL.NS",
  "INDIAMART.NS",
  "PERSISTENT.NS",
  "NAUKRI.NS",
  "MPHASIS.NS",
  "LTIM.NS",
];
